# Generated by Django 5.0.1 on 2024-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nombre")),
                ("surname", models.CharField(max_length=50, verbose_name="Apellidos")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "contact_type",
                    models.IntegerField(
                        choices=[
                            (0, "Pedido de información"),
                            (1, "Reclamaciones de productos"),
                            (2, "Felicitaciones"),
                        ],
                        verbose_name="Motivo de contacto",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Mensaje")),
                (
                    "subscription",
                    models.BooleanField(
                        default=False, verbose_name="Subscripción a la Newsletter"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
            ],
        ),
    ]
